### ISSUE TITLE
Can't install with Go weekly 2012-03-13 on Linux

### ISSUE THREAD

**Issue by codeslinger** [araddon/cass#1]
I am using the following small Go file in order to pull in the cass dependency so I can use it in my code:

```
package main

import (
    "fmt"
    "github.com/araddon/thrift4go"
    "github.com/araddon/cass"
)

func main() {
    fmt.Printf("hi")
}
```

This is with Go weekly, version 2012-03-13 on Ubuntu Linux 11.10.

I get the following errors when trying to build:

```
> go get ./...
package thrift: unrecognized import path "thrift"
package thriftlib/cassandra: unrecognized import path "thriftlib/cassandra"
>
```

Any ideas on how to get cass installed on the weeklies with the new go binary? The instructions for the thrift4go project are old and use goinstall which I fear will no longer work.

**Comment by araddon** [comment]
I pushed up a change that updated the import paths.  Give it a try again

If you have already installed and it didn't work, you might try the " -u"::

```
go get -u github.com/araddon/thrift4go/lib/go/thrift
go get -u github.com/araddon/cass
```

its been a bit of a moving target with the go get tool lately.  I am also working on upstreaming the changes to thrift so the regular install should work there.   Let me know how it goes.

**Comment by codeslinger** [comment]
Perfect! Works great now. Thanks!
